### ISSUE TITLE
running but not sending traffic to graphite server

### ISSUE THREAD

**Issue by pcbadger** [vigne/HAP-Monitor#1]
Hi, I've installed this on centos6 and enabled the socket for haproxy. Strace is showing me lots of this

sendto(3, "haproxy-stats.demo_proxy.Uptime_"..., 49, 0, {sa_family=AF_INET, sin_port=htons(2003), sin_addr=inet_addr("10.1.0.60")}, 16) = 49
sendto(3, "haproxy-stats.demo_proxy.SslCach"..., 50, 0, {sa_family=AF_INET, sin_port=htons(2003), sin_addr=inet_addr("10.1.0.60")}, 16) = 50

Those connection details are right, but according to iptraf, there's nothing going to that IP. I do get this though every time the script polls haproxy

ICMP dest unrch (host) (88 bytes) from 10.1.2.10 to 10.1.2.10 on lo (that's the IP of the haproxy server that the script is running on)

Any suggestions for where I should look to debug this? Also, I'm a little unclear or "user_scope = haproxy-stats" is that something that has to be defined also on the graphite server or just on the haproxy server?

**Comment by vigne** [comment]
Hi,

first I have to make a confession, I kind of forgot that I uploaded this script, and shame on me, left it unmaintained for a while. But, due to your message I revisited it, and changed ... well, pretty much everything. It's now the same as the one I run in production since about 4 months without issues.
So maybe you want to give it a shot?

As for your question, it seems that it fails when it tries to submit the metric to the Graphite server on port 2003. The script uses the pystatsd module (https://pypi.python.org/pypi/pystatsd/) for this. I'm wondering if you have the right version installed? You can check this like this:

```
(.venv)ralph@mcduck:~/Projects/HAP-Monitor$ pip freeze | grep pystats
pystatsd==0.1.10
```

As for the user_sope. No, you don't have to define this anywhere else. Per default, Carbon/Graphite creates new metrics as they are reported. The user scope is just intended to be a prefix where your HAProxy stats are collected. For example:

```
my.stats.ha-proxy.hap-host.3.Idle_pct
```

Here 

*) my.stats.ha-proxy is the user scope, 
*) hap-host is the host name running HAP
*) 3 indicates the process ID (in this case we run 4 process on a quad-core host and this is the third process), and finally 
*) Idle_pct is a metric reported by HAP

I hope this helps, and if you have any further question just contact me again.
Again, apologies for hosting this outdated  version of the script here.

Cheers,
Ralph

**Comment by vigne** [comment]
Hi again,

I also noticed just now that Phillip Roberts made the script way more convenient to use. Maybe you want to consider his version: https://github.com/phillipbroberts/HAP-Monitor/commit/40dfd667603b6cd9b58106321340b19913fb457e

Cheers,
Ralph

**Comment by pcbadger** [comment]
Thanks, that gives "list index out of range" but when I strip down our haproxy.cfg (it's massive) it then sends packets to the graphite server. No graphs are showing up, but I guess that's a whole other set of debugging

**Comment by vigne** [comment]
Can you give any further details on the line where the "list index out of
range" happens?

To check if the metrics are stored by Graphite, check in you file system.
You should finde the Whisper files in the path reflecting the scope.
The default storage folder in Graphite is /opt/graphite/storage/ if I
remember correctly.

**Comment by pcbadger** [comment]
it's immediately upon running the command

/home/vagrant/hap-monitor3.py --backend 10.1.0.60:2003::127.0.0.1:2525 --sockets /var/run/haproxy.sock
2015-04-08 15:10:30,552 7682    ERROR   list index out of range

and here's the verbose output - https://gist.github.com/pcbadger/daead6fd93a1ebd4bb58

**Comment by vigne** [comment]
Hi again,

thanks for the output. It fails when parsing the output of "show stats"
from HAProxy.
To figure out why, could you please tell me the version of HAProxy you're
using? We're running 1.5.3. And maybe provide me a copy of the output from
"show stats "and "show info", so I can have a look?

```
echo "show info" | socat unix-connect:/var/run/haproxy.sock stdio
echo "show stats" | socat unix-connect:/var/run/haproxy.sock stdio
```

In case you wanna have a look yourself, the problem appears between 79 -
89, in line 82 most likely. Probably there is an empty line at the end or
in between, but thats just guessing.

Cheers,
Ralph

**Comment by pcbadger** [comment]
oh ho. I got all the output together, https://gist.github.com/pcbadger/04c2540be79a6e7b3d93 (we're on 1.5.1 but I upgraded to 1.5.3 for testing) and then I noticed something. It only gives that error if I run the command too often. I need to wait about 25 seconds between polling, which is reasonable.

Still need to figure out why graphite isn't doing anything with the output though

**Comment by vigne** [comment]
Hi again,

I wasn't aware of any issue if you run it in shorter intervals, but good to know.

I updated the script to support Graphite and StatsD, because I figured this was the issue, and also, my description wasn't explicit enough. The reason you didn't see any data showing in Graphite was that the Script was reporting to a StatsD/NodeJS as aggregator in front. That's why Graphite couldn't make any sense out of the messages it received and thus ignored them. Anyhow, the updated script now support an additional switch `--type` allowing you to indicate the type of backend you're using. Just add `--type G` to your command and it should work.

Pleas let me know if that solved the issue? For me it worked with data you provided me.

A side note: In case you don't know, Graphite doesn't support gauge values, so if the interval of the script is not in sync with the interval you defined for your data storage in Graphite (e.g one sec in Graphite and one minute in cron) you'll have NULL values in between. To navigate around this issue one can use https://github.com/sivy/node-statsd as an aggregator in front of Graphite. This way you can also record data with 1Hz +, which is also not possible with Graphite.

Cheers,
Ralph

**Comment by pcbadger** [comment]
thanks, but still no luck.  it's certainly sending packets to graphite - UDP (99 bytes) from 10.1.2.10:38759 to 10.1.0.60:2003 on eth1

according to the debug, the message is
2015-04-13 12:21:14,802 14653   DEBUG   Message: localhap.localhost.1.realservice.realservice2.status.MAINT 0.0 1428924074.8

If I throw that same message into a simple python script

#!/usr/bin/env python
import socket
import time
CARBON_SERVER = '10.1.0.60'
CARBON_PORT = 2003
message = 'localhap.localhost.1.realservice.realservice2.status.MAINT 0.0 1428924074.8 \n'
print 'sending message:\n%s' % message
sock = socket.socket()
sock.connect((CARBON_SERVER, CARBON_PORT))
sock.sendall(message)
sock.close()

then that works, but only if I remember to include the  \n in the right place. I've tried moving it about it your script to see if that's the issue, but it hasn't worked so far.

/edit now that I look, it appears to be because the script is sending udp and graphite is listening on tcp.  I threw in statsd (or more precisely, pyhton-bucky on centos) and it looks like it's doing the stuff. I'm going to run with this, presuming I get approval to install a new service

**Comment by vigne** [comment]
Hi,

sorry for the late reply, I was occupied by my daytime job. Yeah, the newline is a little beast. Took me quite some time the first time I started sending messages to Graphite from CLI and than from Python ;-)
The string in the script ends with a newline too (line 108), or do I miss something here?

Unfortunately I can't reproduce the behaviour you observe. All could think of was maybe the time stamp, as it's not integer formatted. I changed this now. But as I said, for me it did work before already.

Yes, in Graphite you have a separate option to open the UDP port on 2003. I figured TCP causes just to much overhead on the interface, especially if you have many client reporting, and thus never tried it.

But going for statsd is definitely a good choice anyway. I makes it way more convenient. It supports rates above 1Hz and also provides additional information like rate, min, max, avg, and what ever you like.
Also it save you plenty of disk space (and IO incase of VM) by allowing you longer intervals but still seeing getting all the important stuff.

I don't know the implementation you chose (pyhton-bucky). We're using a NodeJS module and are pretty happy with it (https://github.com/sivy/node-statsd). In test we made up 50KHz without any issue on a VM(!) and in production we're running about 2 - 2.5Khz without a single issue.

Beside my personal preference of NodeJS it's also a really lightweight multi-tool which is handy in several ways. So, if you're not strictly against it by any reason, I'd give it  a shot.

Let me know if find more bugs.

Cheers,
Raph
